version: "3.4"

services:
  db:
    image: postgres:13.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    logging:
      options:
        max-size: 10m